[package]
name = "internet-mapper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.26"
image = "0.24.5"
tokio = { version = "1.25.0", features = ["full"] }
tokio-icmp-echo = "0.4.1"
